### ISSUE TITLE
WebSocket fails to connect when not on localhost

### ISSUE THREAD

**Issue by timbaas** [WalletConnect/auth-client-js#52]
I'm trying to integrate the AuthClient, which connects successfully when the app is opened on localhost. 
However, when I'm trying to connect when the app is opened from a domain it fails to initiate the websocket to relay.walletconnect.com.

It doesn't provide any errors. My project has the correct allowed domains specified. 

I also tried the example app which gives the same results, it works from localhost but not from a specific domain.

The error in the browser console:
```
ws.ts:114 WebSocket connection to 'wss://relay.walletconnect.com/?auth=jwt&projectId=project-id&ua=wc-2%2Fjs-2.0.0%2Fwindows10-chrome-107.0.0%2Fbrowser%3Ap3041.office.pack.house' failed: 
(anonymous) @ ws.ts:114
register @ ws.ts:112
open @ ws.ts:59
open @ provider.ts:113
connect @ provider.ts:30
init @ index.ts:5
error.ts:66 Uncaught TypeError: Cannot read properties of undefined (reading 'message')
    at parseConnectionError (error.ts:66:12)
    at WsConnection.parseError (ws.ts:160:12)
    at socket.onerror (ws.ts:120:28)
```

**Comment by bkrem** [comment]
Hi @timbaas,

Sorry to hear you're having trouble with getting Auth set up.

We so far haven't seen issues with the client running on a deployment/domain (e.g. https://react-auth-dapp.walletconnect.com/), so this smells to me like some issue around the Allowed Domain configuration, especially since it's not an issue on localhost.

Could you share with us how you've specified `Allowed Domains` for your project and/or share your projectId so we can get a sense of what might be the issue?

cc @devceline @ganchoradkov

**Comment by timbaas** [comment]
Hi @bkrem 

No worries, forgot to mention here that after posting I tried resetting the Project ID after which I was able to connect without a problem. :)

So I guess, this issue can be closed.

Thanks for the reply though!

**Comment by sigra** [comment]
Hi @bkrem 

Having the same problem as TS, but Project ID regeneration didn't help me 😞 . Checked the Allowed domains so many times — domain is certainly correct.

Does WalletConnect have some restrictions for the domain naming? I'm using ngrok for tunneling, can it be a reason of issue?

**Comment by bkrem** [comment]
Hi @sigra,

Thanks for making us aware, reopening since this is still being investigated and clearly still an issue.

I think first steps for us here are to try and remove variables on your side to find what's causing this:
* Does it work if you don't set Allowed Domains?
* Does it work if you use a fresh/regenerated projectId that definitely hasn't had Allowed Domains/Origins set yet?
* Does removing `ngrok` from the scenario change anything?

Would be great if you could share the email account you're using on cloud.walletconnect.com so we can look into your config on our side and try to reproduce separately 🙏 
You can of course also just email me from that address at ben@walletconnect.com if you prefer to not post it here.

**Comment by bkrem** [comment]
FYI: Transferring this issue to the main monorepo since this seems to an infra/config issue, not AuthClient specific.
